### ISSUE TITLE
Remember status on startup

### ISSUE THREAD

**Issue by thnt** [pirackr/Sublime-Bogo#23]
after startup, status of bogo was be reset to **ON**

**Comment by pirackr** [comment]
Hi @Thik,

I'm sorry but I must announce you that this issue will not be fixed. 

I considered about saving the status or reset it at the start up, then I think it's better if we keep the status reset on startup. 

Btw, the default status of Bogo was changed to `OFF` instead of `ON` at the new commit: 4990c2eac27afbfa3c1500df969ab8867f4392aa. I think it's better for programmer since most of their time is for programming (and it don't need Vietnamese input).
